Controllers/LogueoController.cs
namespace LogueoController_space;

using Microsoft.AspNetCore.Mvc;
using UsuarioRepository_space;
using Usuario_space;
public class LogueoController : Controller
{
    readonly IUsuarioRepository _usuarioRepository;
    readonly ILogger<LogueoController> _logger;

    public LogueoController(IUsuarioRepository usuarioRepository, ILogger<LogueoController> logger)
    {
        _usuarioRepository = usuarioRepository;
        _logger = logger;
    }

    [HttpGet]
    public IActionResult Login()
    {
        HttpContext.Session.Clear();
        return View();
    }


    [HttpPost]
    public IActionResult Login(string username, string password)
    {
        try
        {
            List<Usuario> usuarios = _usuarioRepository.ListarUsuarios();
            Usuario? usuario = usuarios.FirstOrDefault(u => u.Nombre == username && u.Password == password);

            if(usuario == null)
            {
                _logger.LogWarning("Intento de acceso inválido - Usuario: " + username + " - Clave: " + password);
                ViewBag.error = "usuario no encontrado";
                return View();
            }

            HttpContext.Session.SetInt32("idUsuario", usuario.Id);
            HttpContext.Session.SetInt32("rol", (int)usuario.RolUsuario);
            HttpContext.Session.SetString("nombre", usuario.Nombre);

            _logger.LogInformation("El usuario "+ usuario.Nombre + " ingresó correctamente");

            return RedirectToAction("Index", "Usuarios");
        }
        catch(Exception ex)
        {
            _logger.LogError(ex.ToString());
            ViewBag.error = "no existen usuarios";
            return View();
        }

    }
}

Views/Logueo/Login.cshtml
@{
    ViewData["Title"] = "Login";
}
@using Kanban.Models
@model Usuario_space.Usuario




@if(ViewBag.error != null && ViewBag.error != "")
{
    <div class="alert alert-warning" role="alert">
        @ViewBag.error
    </div>
}

<header class="mb-5">
    <h1>Logueo</h1>
</header>

<div class="d-flex justify-content-center min-vh-100">
    <form asp-controller="Logueo" asp-action="Login" method="post" class="w-50">

        <div class="form-group">
            <label for="username">Nombre</label>
            <input type="text" asp-for="Nombre" name="username" class="form-control" required>
        </div>

        <div class="mt-3 form-group">
            <label for="password">Contraseña</label>
            <input type="password" asp-for="Password" name="password" class="form-control" required>
        </div>

        <div class="text-center">
            <input type="submit" value="Loguearse" class="mt-3 btn btn-success">
        </div>

        <div class="text-center mt-5 row">

            

            <div class="col">
                <p class="mb-0 text-muted">¿Has olvidado tu contraseña?</p>
                <a asp-action="CambiarPasswordAntes" asp-controller="Usuarios" class="text-info">cambiar contraseña</a>
            </div>
        </div>
    </form>
</div>