Models/Tarea.cs
using System.ComponentModel.DataAnnotations;

namespace Tarea_space;

public class Tarea
{
    [Required]
    int id;
    [Required]
    int idTablero;
    [Required]
    string? nombre;
    string? descripcion;
    string? color;

    EstadoTarea estado;
    int idUsuarioAsignado;

    public int Id { get => id; set => id = value; }

    public int IdTablero { get => idTablero; set => idTablero = value; }

    public string? Nombre { get => nombre; set => nombre = value; }
    
    public string? Descripcion { get => descripcion; set => descripcion = value; }
    public string? Color { get => color; set => color = value; }
    public int IdUsuarioAsignado { get => idUsuarioAsignado; set => idUsuarioAsignado = value; }
    [Required]
    public EstadoTarea Estado { get => estado; set => estado = value; }

    public Tarea(int id, int idTablero, string? nombre, string? descripcion, string? color, int estado, int idUsuarioAsignado)
    {
        this.id = id;
        this.idTablero = idTablero;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.color = color;
        this.estado = (EstadoTarea)estado;
        this.idUsuarioAsignado = idUsuarioAsignado;
    }

    public Tarea(){}
}

public enum EstadoTarea
{
    Ideas = 1,
    ToDo = 2,
    Doing = 3,
    Review = 4,
    Done = 5
}

public interface IEstadoTareaColor
{
    public Dictionary<int, string> ObtenerDiccionario();
}

public class EstadoTareaColor : IEstadoTareaColor
{
    public Dictionary<int, string> _diccionario;

    public EstadoTareaColor()
    {
        _diccionario = new Dictionary<int, string>
        {
            {1, "#82f0f5"},
            {2, "#5d78df"},
            {3, "#b6df5d"},
            {4, "#df5dbf"},
            {5, "#5dbfdf"}
        };
    }

    public Dictionary<int, string> ObtenerDiccionario() => _diccionario;
}

Controllers/TareasController.cs
namespace TareasController_space;

using Microsoft.AspNetCore.Mvc;
using TareaRepository_space;
using Tarea_space;
using UsuarioRepository_space;

public class TareasController : Controller
{
    readonly ITareaRepository _tareaRepository;
    readonly IUsuarioRepository _usuarioRepository;
    readonly IEstadoTareaColor _estadoTareaColor;
    readonly ILogger<TareasController> _logger;

    public TareasController(ITareaRepository tareaRepository, IUsuarioRepository usuarioRepository, IEstadoTareaColor estadoTareaColor, ILogger<TareasController> logger)
    {
        _tareaRepository = tareaRepository;
        _usuarioRepository = usuarioRepository;
        _estadoTareaColor = estadoTareaColor;
        _logger = logger;
    }

    [HttpGet]
    public IActionResult Index()
    {
        return View();
    }

    [HttpGet]
    public IActionResult ListarTareaDeTablero(int id)
    {
        try
        {
            var tareas = _tareaRepository.ListarTareasDeTablero(id);
            return View(tareas);
        }
        catch(Exception ex)
        {
            _logger.LogError(ex.ToString());
            return BadRequest();
        }
    }

    [HttpGet]
    public IActionResult ListarTareaDeUsuario()
    {
        try
        {
            int? id = HttpContext.Session.GetInt32("idUsuario");
            var tareas = _tareaRepository.ListarTareasDeUsuario(id);
            return View(tareas);
        }
        catch(Exception ex)
        {
            _logger.LogError(ex.ToString());
            return BadRequest();
        }
    }

    [HttpGet]
    public IActionResult CrearTarea(int idTablero)
    {
        ViewBag.idTablero = idTablero;
        ViewBag.usuarios = _usuarioRepository.ListarUsuarios();
        return View();
    }

    [HttpPost]
    public IActionResult CrearTarea(Tarea tarea)
    {
        try
        {
            Console.WriteLine((int)tarea.Estado);
            _tareaRepository.CrearTarea(tarea.IdTablero, tarea);
            if (ModelState.IsValid)
            return RedirectToAction("DetalleTablero", "Tableros", new {id = tarea.IdTablero});
            ViewBag.error = "no se pudo crear la tarea";
            ViewBag.idTablero = tarea.IdTablero;
            return View();
        }
        catch(Exception ex)
        {
            _logger.LogError(ex.ToString());
            ViewBag.error = "no se pudo crear la tarea";
            ViewBag.idTablero = tarea.IdTablero;
            return View();
        }
    }

    [HttpGet]
    public IActionResult ModificarTarea(int id)
    {
        var tarea = _tareaRepository.DetallesTarea(id);
        return View(tarea);
    }

    [HttpPost]
    public IActionResult ModificarTarea(int idTablero, Tarea tarea)
    {
        try
        {
            _tareaRepository.ModificarTarea(tarea.Id, tarea);
            if (ModelState.IsValid)
            return RedirectToAction("DetalleTablero", "Tableros", new {id = idTablero});
            ViewBag.error = "no se pudo modificar la tarea";
            return View();
        }
        catch(Exception ex)
        {
            _logger.LogError(ex.ToString());
            ViewBag.error = "no se pudo modificar la tarea";
            return View();
        }
        
    }

    [HttpGet]
    public IActionResult DetalleTarea(int id)
    {
        try
        {
            Tarea tarea = _tareaRepository.DetallesTarea(id);
            ViewBag.usuario = _usuarioRepository.ListarUsuarios().FirstOrDefault(u => u.Id == tarea.IdUsuarioAsignado);
            ViewBag.EstadoTareaColor = _estadoTareaColor.ObtenerDiccionario();
            return View(tarea);
        }
        catch(Exception ex)
        {
            _logger.LogError(ex.ToString());
            return BadRequest();
        }
    }

    [HttpGet]
    [Route("Tareas/EliminarTarea")]
    public IActionResult EliminarTarea(int id)
    {
        var tarea = _tareaRepository.DetallesTarea(id);
        return View(tarea);
    }

    [HttpPost]
    [Route("Tareas/EliminarTareaPost")]
    public IActionResult EliminarTarea(Tarea tarea)
    {
        try
        {
            _tareaRepository.EliminarTarea(tarea.Id);
            if (ModelState.IsValid)
            return RedirectToAction("DetalleTablero", "Tableros", new {id = tarea.IdTablero});
            ViewBag.error = "no se pudo eliminar la tarea";
            return View();
        }
        catch(Exception ex)
        {
            _logger.LogError(ex.ToString());
            ViewBag.error = "no se pudo eliminar la tarea";
            return View();
        }
    }
}

Views/Tareas/CrearTarea.cshtml
@{
    ViewData["Title"] = "Crear Tarea";
}
@using Kanban.Models
@model Tarea_space.Tarea

@section Scripts{<partial name="_ValidationScriptsPartial"/>}

@if(ViewBag.error != null && ViewBag.error != "")
{
    <div class="alert alert-warning" role="alert">
        @ViewBag.error
    </div>
}

<h1 class="mb-5">Crear Tarea</h1>

<form asp-controller="Tareas" asp-action="CrearTarea" method="post">

    <input type="hidden" value="0" asp-for="Id">
    <input type="hidden" value="@ViewBag.idTablero" asp-for="IdTablero">

    <div class="form-group">
        <label for="Nombre">Nombre</label>
        <input type="text" asp-for="Nombre" name="Nombre" id="Nombre" class="form-control" required>
    </div>

    <div class="mt-3 form-group">
        <label for="descripcion">Descripción</label>
        <input type="text" asp-for="Descripcion" name="descripcion" id="descripcion" class="form-control">
    </div>

    <div class="mt-3 form-group">

        <label for="usuario">Usuario asignado</label>
        <select asp-for="IdUsuarioAsignado" class="form-select" id="usuario">
            @foreach(var u in ViewBag.usuarios)
            {
                <option value="@u.Id">@u.Nombre</option>
            }
        </select>
    </div>

    <div class="mt-3 form-group">
        <label for="color">Color</label>
        <input type="color" asp-for="Color" name="color" id="color" value="#fdec85" class="form-control" oninput="this.nextElementSibling.value = this.value">
        <input type="text" readonly value="#ff0000">
    </div>

    <div class="mt-3 form-group">
        <label for="estado">Estado</label>
        <select name="Estado" id="estado" asp-for="Estado" class="form-select">
            <option value="@Tarea_space.EstadoTarea.Ideas" selected>Idea</option>
            <option value="@Tarea_space.EstadoTarea.ToDo">ToDo</option>
            <option value="@Tarea_space.EstadoTarea.Doing">Doing</option>
            <option value="@Tarea_space.EstadoTarea.Review">Review</option>
            <option value="@Tarea_space.EstadoTarea.Done">Done</option>
        </select>
    </div>

    <div class="text-center">
        <input type="submit" value="Crear" class="mt-3 btn btn-success">
    </div>
</form>

Views/Tareas/DetalleTarea.cshtml
@{
    ViewData["Title"] = "Detalle de tarea";
    int? idUsuario = Context.Session.GetInt32("idUsuario");
    string colorAsignado = "#b2fd85";
    string colorEstado = ViewBag.EstadoTareaColor[(int)Model.Estado];
}
@using Kanban.Models
@model Tarea_space.Tarea

<style>
    #asignado
    {
        padding: 1%;
        background-color: @colorAsignado;
        height: auto;
        border-radius: 10px;
    }

    #color
    {
        background-color: @Model.Color;
        padding: 2%;
        border-radius: 10px;
    }

    #estado
    {
        padding: 1%;
        background-color: @colorEstado;
        border-radius: 10px;
    }
</style>


<header class="mb-5">
    <h1>Tarea: @Model.Nombre</h1>
</header>

<div>
    <div class="descripcion mb-3">
        <h3>Descripción</h3>
        <p class="m-0">@Model.Descripcion</p>
    </div>

    <div id="asignado" class="mb-3">
        @if(ViewBag.usuario != null)
        {
            colorAsignado = "#b2fd85";
            <p>Asignado a:<b> @ViewBag.usuario.Nombre</b></p>
        }
        else
        {
            colorAsignado = "#fd8585";
            <p>Tarea no asignada</p>
        }
    </div>

    <div id="color" class="text-center mb-3">
        <p><b>COLOR</b></p>
    </div>

    <div class="mb-3" id="estado">
        <p>Estado: <b>@Model.Estado</b></p>
    </div>

    @if(Model.IdUsuarioAsignado == idUsuario)
    {
        <a asp-action="ModificarTarea" asp-controller="Tareas" asp-route-id="@Model.Id" class="btn btn-primary">Cambiar Estado</a>
    }
</div>


Views/Tareas/EliminarTarea.cshtml
@{
    ViewData["Title"] = "Eliminar Tarea";
}
@using Kanban.Models
@model Tarea_space.Tarea

@if(ViewBag.error != null && ViewBag.error != "")
{
    <div class="alert alert-warning" role="alert">
        @ViewBag.error
    </div>
}

<h1 class="mb-5">Eliminar Tarea</h1>

<div class="d-flex justify-content-center min-vh-100">
<form method="post" asp-action="EliminarTareaPost" asp-controller="Tareas">
    <legend class="text-center">¿Está seguro que desea eliminar la tarea @Model.Nombre?</legend>

    <input type="hidden" value="@Model.Id" asp-for="Id">
    <input type="hidden" value="@Model.Nombre" asp-for="Nombre">
    <input type="hidden" value="@Model.Descripcion" asp-for="Descripcion">
    <input type="hidden" value="@Model.Color" asp-for="Color">
    <input type="hidden" value="@Model.IdTablero" asp-for="IdTablero">
    <input type="hidden" value="@Model.IdUsuarioAsignado" asp-for="IdUsuarioAsignado">

    <div class="form-group row">
        <div class="col text-center">
            <input type="submit" class="btn btn-danger px-3" value="Si">
        </div>
        <div class="col text-center">
            <a asp-action="DetalleTablero" asp-controller="Tableros" asp-route-id="@Model.IdTablero" class="btn btn-primary">No</a>
        </div>
    </div>
</form>
</div>

Views/Tareas/ModificarTarea.cshtml
@{
    ViewData["Title"] = "Cambiar estado de tarea";
}
@using Kanban.Models
@model Tarea_space.Tarea

@section Scripts{<partial name="_ValidationScriptsPartial"/>}

<header class="mb-5">
    <h1>Cambiar estado de tarea</h1>
</header>

<form asp-action="ModificarTarea" asp-controller="Tareas" method="post">
    <legend>Cambiar estado de tarea: @Model.Nombre</legend>
    <input type="hidden" value="@Model.Id" asp-for="Id">
    <input type="hidden" value="@Model.Nombre" asp-for="Nombre">
    <input type="hidden" value="@Model.Descripcion" asp-for="Descripcion">
    <input type="hidden" value="@Model.Color" asp-for="Color">
    <input type="hidden" value="@Model.IdTablero" asp-for="IdTablero">
    <input type="hidden" value="@Model.IdUsuarioAsignado" asp-for="IdUsuarioAsignado">
    
    <div class="mt-3 form-group">
        <label for="estado">Estado</label>
        <select name="Estado" id="estado" asp-for="Estado" class="form-select">
            <option value="@Tarea_space.EstadoTarea.Ideas">Idea</option>
            <option value="@Tarea_space.EstadoTarea.ToDo">ToDo</option>
            <option value="@Tarea_space.EstadoTarea.Doing">Doing</option>
            <option value="@Tarea_space.EstadoTarea.Review">Review</option>
            <option value="@Tarea_space.EstadoTarea.Done">Done</option>
        </select>
    </div>

    <input type="submit" class="btn btn-primary mt-3" value="cambiar">
</form>